### ISSUE TITLE
No rustfmt ?

### ISSUE THREAD

**Issue by YievCkim** [rayliwell/rstml-ts-mode#1]
Hi,

First, Thank you for this package. 

On old rust-mode, I had the possibility to run rustfmt on a buffer. I didn't find this feature on this mode. I tried to setup format-all for that but I get an error when I try it:
```
format-all--prompt-for-formatter: No supported formatters for this language
```

I tried to configure format-all for that but I didn't know how to configure it. I need to provide a language name . Rust is already set (and don't work). I tried several thing rustml, rust with html, rust_with_html, etc... nothing work. Is there a way to have rustfmt with this mode ?

**Comment by rayliwell** [comment]
Assuming it's based on the string form of the mode name, I think should be: "Rust with rstml"

**Comment by YievCkim** [comment]
I tried it, and it doesn't work sadly. Any plan to add old rust-mode tooling into rust-ts-mode and rstml-ts-mode ?

I made an issue to format-all https://github.com/lassik/emacs-format-all-the-code/issues/259

Maybe they have a solution

**Comment by YievCkim** [comment]
Worth to know when I try `C-c C-f` from rust-ts-mode I got another error too:

"Wrong type argument: commandp, rust-format-buffer"

So maybe it's an issue with rust-ts-mode

**Comment by rayliwell** [comment]
You'll have to add `rstml-ts-mode` to [this list](https://github.com/lassik/emacs-language-id/blob/44452e4f7962aca41cc2539fce1d27799d6e656c/language-id.el#L246) in `language-id--definitions`.

To be honest with you though, I'd recommend just using apheleia and modifying `apheleia-mode-alist`.

**Comment by YievCkim** [comment]
aaah ok...

Thank you to investigate this... I have no idea If I can change this list the package come from melpa and it will be updated on the next upgrade. 

I didn't know apheleia, thank you I am going to give it a try.

**Comment by YievCkim** [comment]
Thank you @rayliwell I have switched on apheleia and apart from the fact that the mode name could be more memory-friendly, it works perfectly.

**Comment by rayliwell** [comment]
No worries buddy, happy you got it working.

A star on the repo is always appreciated :)
